# yaml file for configuring how readthedocs processes the documentation
# Refer to https://docs.readthedocs.io/en/stable/config-file/v2.html for details.

# Version of readthedoc's config style
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-24.04
  tools:
    python: "3.12"

# Path to sphinx's configuration file
sphinx:
  configuration: docs/conf.py

# Build pdf and htmlzip files in addition to the html documentation
formats:
  - pdf

# Additional requirements for the documentation
python:
  install:
    - method: pip
      path: .
    - requirements: requirements/requirements-documentation.txt
